[package]
name = "wallet-desktop"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Tauri-based desktop wallet for Aevum & Bond"

[dependencies]
serde.workspace = true
